/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomDevelopmentRouteImport } from './routes/custom-development'
import { Route as FacilityRouteImport } from './routes/facility'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as OemRouteImport } from './routes/oem'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AboutMissionRouteImport } from './routes/about.mission'
import { Route as AboutNetworkRouteImport } from './routes/about.network'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as TechnologyIndexRouteImport } from './routes/technology.index'
import { Route as TechnologySlugRouteImport } from './routes/technology.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomDevelopmentRoute = CustomDevelopmentRouteImport.update({
  id: '/custom-development',
  path: '/custom-development',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityRoute = FacilityRouteImport.update({
  id: '/facility',
  path: '/facility',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const OemRoute = OemRouteImport.update({
  id: '/oem',
  path: '/oem',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMissionRoute = AboutMissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => AboutRoute,
} as any)
const AboutNetworkRoute = AboutNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AboutRoute,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyIndexRoute = TechnologyIndexRouteImport.update({
  id: '/technology/',
  path: '/technology/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologySlugRoute = TechnologySlugRouteImport.update({
  id: '/technology/$slug',
  path: '/technology/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/custom-development': typeof CustomDevelopmentRoute
  '/facility': typeof FacilityRoute
  '/faq': typeof FaqRoute
  '/insights': typeof InsightsRouteWithChildren
  '/oem': typeof OemRoute
  '/quality': typeof QualityRoute
  '/research': typeof ResearchRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/network': typeof AboutNetworkRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/technology/$slug': typeof TechnologySlugRoute
  '/products/': typeof ProductsIndexRoute
  '/technology/': typeof TechnologyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/custom-development': typeof CustomDevelopmentRoute
  '/facility': typeof FacilityRoute
  '/faq': typeof FaqRoute
  '/insights': typeof InsightsRouteWithChildren
  '/oem': typeof OemRoute
  '/quality': typeof QualityRoute
  '/research': typeof ResearchRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/network': typeof AboutNetworkRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/technology/$slug': typeof TechnologySlugRoute
  '/products': typeof ProductsIndexRoute
  '/technology': typeof TechnologyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/custom-development': typeof CustomDevelopmentRoute
  '/facility': typeof FacilityRoute
  '/faq': typeof FaqRoute
  '/insights': typeof InsightsRouteWithChildren
  '/oem': typeof OemRoute
  '/quality': typeof QualityRoute
  '/research': typeof ResearchRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/network': typeof AboutNetworkRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/technology/$slug': typeof TechnologySlugRoute
  '/products/': typeof ProductsIndexRoute
  '/technology/': typeof TechnologyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/custom-development'
    | '/facility'
    | '/faq'
    | '/insights'
    | '/oem'
    | '/quality'
    | '/research'
    | '/resources'
    | '/sitemap.xml'
    | '/about/mission'
    | '/about/network'
    | '/insights/$slug'
    | '/products/$slug'
    | '/technology/$slug'
    | '/products/'
    | '/technology/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/custom-development'
    | '/facility'
    | '/faq'
    | '/insights'
    | '/oem'
    | '/quality'
    | '/research'
    | '/resources'
    | '/sitemap.xml'
    | '/about/mission'
    | '/about/network'
    | '/insights/$slug'
    | '/products/$slug'
    | '/technology/$slug'
    | '/products'
    | '/technology'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/custom-development'
    | '/facility'
    | '/faq'
    | '/insights'
    | '/oem'
    | '/quality'
    | '/research'
    | '/resources'
    | '/sitemap.xml'
    | '/about/mission'
    | '/about/network'
    | '/insights/$slug'
    | '/products/$slug'
    | '/technology/$slug'
    | '/products/'
    | '/technology/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  ContactRoute: typeof ContactRoute
  CustomDevelopmentRoute: typeof CustomDevelopmentRoute
  FacilityRoute: typeof FacilityRoute
  FaqRoute: typeof FaqRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  OemRoute: typeof OemRoute
  QualityRoute: typeof QualityRoute
  ResearchRoute: typeof ResearchRoute
  ResourcesRoute: typeof ResourcesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  TechnologySlugRoute: typeof TechnologySlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  TechnologyIndexRoute: typeof TechnologyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-development': {
      id: '/custom-development'
      path: '/custom-development'
      fullPath: '/custom-development'
      preLoaderRoute: typeof CustomDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility': {
      id: '/facility'
      path: '/facility'
      fullPath: '/facility'
      preLoaderRoute: typeof FacilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oem': {
      id: '/oem'
      path: '/oem'
      fullPath: '/oem'
      preLoaderRoute: typeof OemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/mission': {
      id: '/about/mission'
      path: '/mission'
      fullPath: '/about/mission'
      preLoaderRoute: typeof AboutMissionRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/network': {
      id: '/about/network'
      path: '/network'
      fullPath: '/about/network'
      preLoaderRoute: typeof AboutNetworkRouteImport
      parentRoute: typeof AboutRoute
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology/': {
      id: '/technology/'
      path: '/technology'
      fullPath: '/technology/'
      preLoaderRoute: typeof TechnologyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology/$slug': {
      id: '/technology/$slug'
      path: '/technology/$slug'
      fullPath: '/technology/$slug'
      preLoaderRoute: typeof TechnologySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AboutRouteChildren {
  AboutMissionRoute: typeof AboutMissionRoute
  AboutNetworkRoute: typeof AboutNetworkRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutMissionRoute: AboutMissionRoute,
  AboutNetworkRoute: AboutNetworkRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  ContactRoute: ContactRoute,
  CustomDevelopmentRoute: CustomDevelopmentRoute,
  FacilityRoute: FacilityRoute,
  FaqRoute: FaqRoute,
  InsightsRoute: InsightsRouteWithChildren,
  OemRoute: OemRoute,
  QualityRoute: QualityRoute,
  ResearchRoute: ResearchRoute,
  ResourcesRoute: ResourcesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  TechnologySlugRoute: TechnologySlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  TechnologyIndexRoute: TechnologyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
